export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CHECK_REGISTER_USER = "CHECK_REGISTER_USER";
export const REGISTER_PROCESS = "REGISTER_PROCESS";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const SEND_MESSAGE_PENDING = "SEND_MESSAGE_PENDING";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";
export const SEND_MESSAGE_SCREEN = "SEND_MESSAGE_SCREEN";

export const GET_USER_NOTIFICATIONS = "GET_USER_NOTIFICATIONS";
export const PEND_USER_NOTIFICATIONS = "PEND_USER_NOTIFICATIONS";
export const PEND_USER_NOTIFICATIONS_SUCCESS = "PEND_USER_NOTIFICATIONS_SUCCESS";
export const PEND_USER_NOTIFICATIONS_FAILURE = "PEND_USER_NOTIFICATIONS_FAILURE";